# Einführung in Numpy

Zuerst einmal Benchmarking: Numpy ist viel schneller und effizienter als das Arbeiten mit herkömmlichen Datenstrukturen.

In [2]:
import timeit
import numpy as np

arr = np.arange(1e7)

larr = arr.tolist()

def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = scalar * val

N = 10

# NumPy array broadcasting
time1 = timeit.timeit('1.1 * arr', 'from __main__ import arr', number=N)
time1 /= N
print("Average time for NumPy broadcasting: ", time1)
# List and custom function for broadcasting
time2 = timeit.timeit('list_times(larr, 1.1)',
'from __main__ import list_times, larr', number=N)
time2 /= N
print("Average time for using a list: ", time2)
print("NumPy gives us an acceleration of factor ", int(time2/time1))

Average time for NumPy broadcasting:  0.008165729200000093
Average time for using a list:  0.7121074292000001
NumPy gives us an acceleration of factor  87


# Arrays mit speziellen Elementen

Man kann spezielle Arrays mit leeren Elementen oder anderen speziellen Werten erzeugen:

In [3]:
# Creating an empty array with given shape
arr = np.empty(shape=(2, 2), dtype=np.float64)
print('np.empty')
print(arr)
# Creating an array of zeros with five elements
arr = np.zeros(5)
print('np.zeros')
print(arr)
# Creating an array of ones with five elements
arr = np.ones(5)
print('np.ones')
print(arr)
# Create the identy matrix
arr = np.eye(N=4, dtype=np.float32)
print('np.eye')
print(arr)
# Create a matrix filled with a given value
arr = np.full(shape=(2, 3), fill_value=2.0)
print('np.full')
print(arr)

np.empty
[[-2.31584178e+077 -2.31584178e+077]
 [ 4.33222861e-311  2.82466461e-309]]
np.zeros
[0. 0. 0. 0. 0.]
np.ones
[1. 1. 1. 1. 1.]
np.eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
np.full
[[2. 2. 2.]
 [2. 2. 2.]]


... oder mit speziellen Zahlenbereichen:

In [4]:
# What if we want to create an array going from 0 to 100?
arr = np.arange(101)
# Or 10 to 100?
arr = np.arange(10, 101)
# If you want 100 steps from 0 to 1...
arr = np.linspace(0, 1, 100)
# Or if you want to generate an array from 1 to 10
# in log10 space in 10 steps...
arr = np.logspace(start=0.0, stop=1.0, num=10, endpoint=True, base=10.0)
print("An array in logspace ", arr)

An array in logspace  [ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


## Reshaping

In [5]:
arr1d = np.arange(1000)
print(arr1d.shape)
# Now reshaping the array to a 10x10x10 3D array
arr3d = arr1d.reshape((10, 10, 10))
# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (10, 10, 10))
# Inversely, we can flatten arrays
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()
print(arr1d.shape)

(1000,)
(10000,)


## Indexing und Slicing

In [6]:
alist = [[1, 2], [3, 4]]
# To return the (0,1) element we must index as shown below.
print("alist[0, 1] = ", alist[0][1])
# Converting the list defined above into an array
arr = np.array(alist)
# To return the (0,1) element we use ...
print("arr[0, 1] = ", arr[0, 1])
# Now to access the last column, we simply use ...
print("the last column of arr: ", arr[:, 1])
# Accessing the rows is achieved in the same way.
print("the last row of arr: ", arr[1, :])

alist[0, 1] =  2
arr[0, 1] =  2
the last column of arr:  [2 4]
the last row of arr:  [3 4]


### Indexmengen

In [7]:
# Creating an array
arr = np.arange(5)
# Creating the index array
index = np.where(arr > 2)
print("the index array for arr>2: ", index)
# Creating the desired array
new_arr = arr[index]
print("the new array with the index array: ", new_arr)

# logical values
index = arr > 2
print("the boolean index array for arr>2: ", index)
new_arr = arr[index]
print("the new array with the boolean index array: ", new_arr)

the index array for arr>2:  (array([3, 4]),)
the new array with the index array:  [3 4]
the boolean index array for arr>2:  [False False False  True  True]
the new array with the boolean index array:  [3 4]


### Slicing

In [8]:
arr = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr)
print("arr[:, 1]: ", arr[:, 1])
print("arr[:, 1:]: ", arr[:, 1:])
print("arr[:, 0:2]: ", arr[:, 0:2])
print("arr[0, :]: ", arr[0, :])

[[1 2 3]
 [4 5 6]]
arr[:, 1]:  [2 5]
arr[:, 1:]:  [[2 3]
 [5 6]]
arr[:, 0:2]:  [[1 2]
 [4 5]]
arr[0, :]:  [1 2 3]


### Kopien und Referenzen

In [9]:
arr1d = np.arange(1000)
arr3d = arr1d.reshape((10, 10, 10))
print("arr3d[0, 0, 2] = ", arr3d[0, 0, 2])
# Change the value of arr1d[2]
arr1d[2] = 42.0
print("\narr3d[0, 0, 2] = ", arr3d[0, 0, 2])
# restore the values
arr1d[2] = 2.0
# a copy of arr1d
arr1d_new = arr1d.copy()
# Change arr1d[2] again ...
arr1d[2] = 42.0
print("\narr1d[2] = ", arr1d[2])
print("arr1d_new[2] = ", arr1d_new[2])

arr3d[0, 0, 2] =  2

arr3d[0, 0, 2] =  42

arr1d[2] =  42
arr1d_new[2] =  2


### Mathematische Funktionen in NumPy

In [10]:
a = np.arange(10, 50, 10)
b = np.arange(4)
print("a = ", a)
print("b = ", b)
c = a - b
print("\na-b = ", c)
print("b**2 = ", b**2)
d = 5.0 * np.sqrt(a)
print("5.0 * np.sqrt(a) =", d)
print("inner product np.dot(a, b) = ", np.dot(a, b))
e1 = np.array([1.0, 0.0, 0.0], dtype=np.float64)
e2 = np.array([0.0, 1.0, 0.0], dtype=np.float64)
print("vector product np.cross(e1, e2) = ", np.cross(e1, e2))

a =  [10 20 30 40]
b =  [0 1 2 3]

a-b =  [10 19 28 37]
b**2 =  [0 1 4 9]
5.0 * np.sqrt(a) = [15.8113883  22.36067977 27.38612788 31.6227766 ]
inner product np.dot(a, b) =  200
vector product np.cross(e1, e2) =  [0. 0. 1.]


### Zweidimensionale Arrays

In [11]:
a = np.arange(4.0).reshape((2, 2))
print("\nmatrix a =\n", a)
b = a+2
print("\nmatrix b =\n", b)
# elementwise multiplication
c = a*b
print("\nmatrix a*b =\n", c)
# matrix multiplication
c = np.dot(a, b)
print("\nmatrix np.dot(a, b) =\n", c)


matrix a =
 [[0. 1.]
 [2. 3.]]

matrix b =
 [[2. 3.]
 [4. 5.]]

matrix a*b =
 [[ 0.  3.]
 [ 8. 15.]]

matrix np.dot(a, b) =
 [[ 4.  5.]
 [16. 21.]]


### Arithmetik

In [12]:
a = np.ones((3, 2))
b = np.arange(6).reshape(3, 2)
print("\nmatrix a =\n", a)
print("matrix b =\n", b)
b += 1
print("result for b += 1 = \n", b)
c = a
c += 3.0*a
print("matrix a += 3.0*a =\n", c)


matrix a =
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
matrix b =
 [[0 1]
 [2 3]
 [4 5]]
result for b += 1 = 
 [[1 2]
 [3 4]
 [5 6]]
matrix a += 3.0*a =
 [[4. 4.]
 [4. 4.]
 [4. 4.]]


### Hilfsfunktionen

In [13]:
print("\nb.min() = ", b.min())
print("b.max() = ", b.max())
print("b.sum() = ", b.sum())


b.min() =  1
b.max() =  6
b.sum() =  21
